version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./laravel_app:/var/www/html/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    php:
        image: spalacios/php_73_fpm:v.1.0.0
        volumes:
            - ./laravel_app:/var/www/html/src
            - ~/.composer:/var/www/.composer
        networks:
            - code-network

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3306:3306"
        expose:
            - "3306"
        networks:
            - code-network
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./dumps:/dumps

    elasticsearch:
        image: elasticsearch:7.4.1
        ports:
            -  "9200:9200"
            -  "9300:9300"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.type=single-node"
        volumes:
            - "./data/elasticsearch:/usr/share/elasticsearch/data"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
